#!/usr/bin/env bash
# launcher
# deps: rofi
set -euo pipefail
LC_ALL=C

# --- Config ------------------------------------------------------------------
ROFI_BIN="${ROFI_BIN:-rofi}"
ROFI_ARGS="${ROFI_ARGS:--show drun -config $HOME/.config/rofi/themes/dmenu-launcher.rasi}"

$ROFI_BIN $ROFI_ARGS
