#!/usr/bin/env bash

THEME="$HOME/.config/rofi/themes/powermenu.rasi"
UPTIME="$(uptime -p | sed -e 's/up //g')"

# Options
shutdown=""
reboot="󱄌"
lock=""
suspend=""
logout="󰿅"

rofi_cmd() {
  rofi -dmenu \
    -p "Goodbye ${USER}" \
    -mesg "Uptime: $UPTIME" \
    -theme $THEME
}

run_rofi() {
  echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
  if [[ $1 == '--shutdown' ]]; then
    systemctl poweroff
  elif [[ $1 == '--reboot' ]]; then
    systemctl reboot
  elif [[ $1 == '--suspend' ]]; then
    systemctl suspend
  elif [[ $1 == '--logout' ]]; then
    if uwsm check is-active; then
      uswm stop
    else
      loginctl terminate-session
    fi
  elif [[ $1 == '--lock' ]]; then
    loginctl lock-session
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$shutdown)
  run_cmd --shutdown
  ;;
$reboot)
  run_cmd --reboot
  ;;
$lock)
  run_cmd --lock
  ;;
$suspend)
  run_cmd --suspend
  ;;
$logout)
  run_cmd --logout
  ;;
esac
