#!/usr/bin/env bash

# Current Theme
dir="$HOME/.config/rofi/themes/"
theme='powermenu'

# CMDs
uptime="$(uptime -p | sed -e 's/up //g')"

# Options
shutdown=""
reboot="󱄌"
lock=""
suspend=""
logout="󰿅"

# Rofi CMD
rofi_cmd() {
  rofi -dmenu \
    -p "Goodbye ${USER}" \
    -mesg "Uptime: $uptime" \
    -theme ${dir}/${theme}.rasi
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "$lock\n$suspend\n$logout\n$reboot\n$shutdown" | rofi_cmd
}

# Execute Command
run_cmd() {
  if [[ $1 == '--shutdown' ]]; then
    systemctl poweroff
  elif [[ $1 == '--reboot' ]]; then
    systemctl reboot
  elif [[ $1 == '--suspend' ]]; then
    systemctl suspend
  elif [[ $1 == '--logout' ]]; then
    if [[ "$XDG_SESSION_DESKTOP" == 'Hyprland' ]]; then
      uswm stop
    else
      loginctl terminate-session
    fi
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$shutdown)
  run_cmd --shutdown
  ;;
$reboot)
  run_cmd --reboot
  ;;
$lock)
  if [[ -x '/usr/bin/hyprlock' ]]; then
    locker "lock"
    sleep 0.5
    hyprlock -q
    locker "unlock"
  fi
  ;;
$suspend)
  run_cmd --suspend
  ;;
$logout)
  run_cmd --logout
  ;;
esac
