[tools]
uv = "latest"
pipx = "latest"
go = "latest"
rust = "latest"
opentofu = "latest"
terragrunt = "latest"
terraform = "latest"
ansible = "latest"
node = "26"
kubectl = "latest"
helm = "latest"
azure-cli = "latest"
azure-kubelogin = "latest"
helmfile = "latest"
kubeconform = "latest"
kubie = "latest"
